server:
  port: 8761
debug: true
spring:
  application:
    name: registry
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#eureka:
#  instance:
#    hostname:

